from django.db import models

# Create your models here.
class Question(models.Model):
   text = models.CharField(max_length = 10000)
   correct = models.ForeignKey('Answer', related_name = 'corrected', null = True)
   revoked = models.BooleanField()
   image = models.URLField()
   subelement = models.CharField(max_length = 2)
   section = models.CharField(max_length = 1)
   number = models.CharField(max_length = 2)
   reference = models.CharField(max_length = 100)

class Answer(models.Model):
   text = models.CharField(max_length = 10000)
   question = models.ForeignKey(Question, null = True)

#class Exam(models.Model):
   #question1 = models.ForeignKey(Question)
   #question2 = models.ForeignKey(Question)
   #question3 = models.ForeignKey(Question)
   #question4 = models.ForeignKey(Question)
   #question5 = models.ForeignKey(Question)
   #question6 = models.ForeignKey(Question)
   #question7 = models.ForeignKey(Question)
   #question8 = models.ForeignKey(Question)
   #question9 = models.ForeignKey(Question)
   #question10 = models.ForeignKey(Question)
   #question11 = models.ForeignKey(Question)
   #question12 = models.ForeignKey(Question)
   #question13 = models.ForeignKey(Question)
   #question14 = models.ForeignKey(Question)
   #question15 = models.ForeignKey(Question)
   #question16 = models.ForeignKey(Question)
   #question17 = models.ForeignKey(Question)
   #question18 = models.ForeignKey(Question)
   #question19 = models.ForeignKey(Question)
   #question20 = models.ForeignKey(Question)
   #question21 = models.ForeignKey(Question)
   #question22 = models.ForeignKey(Question)
   #question23 = models.ForeignKey(Question)
   #question24 = models.ForeignKey(Question)
   #question25 = models.ForeignKey(Question)
   #question26 = models.ForeignKey(Question)
   #question27 = models.ForeignKey(Question)
   #question28 = models.ForeignKey(Question)
   #question29 = models.ForeignKey(Question)
   #question30 = models.ForeignKey(Question)
   #question31 = models.ForeignKey(Question)
   #question32 = models.ForeignKey(Question)
   #question33 = models.ForeignKey(Question)
   #question34 = models.ForeignKey(Question)
   #question35 = models.ForeignKey(Question)
